name: github action
on:
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo hello word, today is $TODAY
  settup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.3
      - name: setup run npm
        run: npm install
      - name: run eslint
        run: npm run lint -- --fix
      - name: run build
        run: npm run build


